<?xml version="1.0" encoding="UTF-8"?>

<!--
This file gives a table of Bible booknames codes including
these six compulsory fields:
    The IETF2 original language code, e.g., hbo, el-x-koine, lat (Can be comma separated list)
    An original language (e.g., Hebrew, Greek) book name; can be a forward slash separated list)
    An English book name (as a guide or comment only; can be a forward slash separated list)
    A three-character reference code (upper case, no spaces, begins with a letter)
        This reference code should reflect book contents (not book names) and is used to link to other tables.
        These reference codes are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
    A reference number (1..899 for processing only - not necessarily consecutive or sequential)
        Reference numbers are guaranteed to be stable after V1.00
            i.e., they will not change or be reused for different books.
        Can be used as a unique ID instead of the reference code if you prefer an integer.
        1..66 are guaranteed to match the common Protestant Bible book orders.
        900..999 are reserved for user defined books and are not defined here.
    A sequence number or typical book order number (1..999 for comparing the order only - not necessarily consecutive)
        Only to be used if there is no better information about which order that books are intended to be published in.
        Only the relative value of this field is important (smaller or bigger) - the actual values are meaningless.
and then these optional fields (optional because not all systems handle the less common or more disputed books)
    The number of expected chapters in this book (alternatives are separated by commas).
        This is not authorative, but can assist in identifying books where the encoding is otherwise ambiguous.
    The SBL abbreviation (can include spaces)
    The OSIS abbreviation (no spaces but may begin with a digit)
    The Sword abbreviation
    The 1-2 digit CCEL ID number
    The three-character USFM abbreviation (no spaces but may begin with a digit)
        Also used for Paratext Bible editor and Digital Bible Library (DBL) bundles
    The two-digit USFM ID number
        UBS/SIL Paratext uses both the number and the abbreviation above (and USFM format)
        These are obtained from https://ubsicap.github.io/usfm/identification/books.html
    The three-digit USX ID number
        UBS/SIL Paratext can export to USX files
    The 1-2 digit Bibledit ID number
    The Faithlife Logos ID number (Can be used online as n in ref.ly/logosref/bible.n)
        These were obtained from https://github.com/Clear-Bible/Biblelib/blob/main/biblelib/books/books.tsv
    The 2-7 character Logos abbreviation from https://wiki.logos.com/COM_API_Bible_Book_Abbreviations
    The three-character NET Bible abbreviation
    The three-character DrupalBible abbreviation
    The 2-4 character Bible abbreviation used for the Robinson-Pierpont Byzantine Greek text
    Alternative abbreviations (upper case, separated by commas, optional)
        These abbreviations might typically be used in VPL (verse per line) Bibles
          but they're also likely to be used in section references and cross-references,
          basically any name or shortened name which might be used to name an English book
          (and mispellings may even be included)
        These also automatically have spaces removed
          and get shortened versions during processing
          (but not shortened so far as to be ambiguous, e.g., GEN and GAL could be shortened to GE and GA but not G)
    Possible alternative book codes (separated by commas)
        This is not precise but roughly shows which book this book might be confused with.
        It is used for automatic mapping of book codes (also using the expected number of chapters)
    Consists of book codes (separated by commas)
        Where a single book might be a combination of two or more individual books
    The name of a typical section containing this book (in the set OT, OT+, NT, NT+, DC, PS, FRT, BAK)
    The name of a typical sub-section containing this book (in the set Pentateuch, Historical, Poetry-Wisdom, Major Prophets, Minor Prophets, Gospels, Acts, Paul's Letters, General Letters, Revelation)
Most of the above fields should individually be unique, but there are some many-to-one mappings.
    e.g., Paratext uses the same code for Ezra as for Ezra-Nehemiah. (We make available separate codes.)

The information in this table should be language agnostic although English is used as a meta-language.
It should also be independent of any theological judgements but mostly based on historical publications.
The main aim is to supply an inventory of book codes which are recognised by the BibleOrgSsy Bible Organisational System.

Deutero-canonical/Apocryphal and less common books are included, even pseudegrapha.
"Combined" books are included.
This table does not infer any information about the quality or theological usefulness of any particular book.
This table does not infer any information about the presence or the order of the books within any particular publication.
This table is not authoritative about the number of chapters (or verses) in any given book in any particular publication.
There should be exactly one entry for each possible Bible book which is printed separately in some publications
    and one entry for each possible combination of those Bible books.
For example:
    If Ezra and Nehemiah are sometimes published as individual books, and sometimes combined, there should be three entries in this database.
    If Hebrew Esther and Greek Esther are sometimes published as individual books, and sometimes combined, there should be 3 entries in this database.
        However, if Greek Esther was never published singly, but only in combination with Hebrew Esther, there would only be 2 entries (Hebrew Esther and Combined Esther).
    This is because mappings between/across Bible books in different publications will be dependent on this file.
        (If it's JUST that chapters and verses are divided up differently WITHIN a book, that's handled elsewhere.)
    If a book is a translation of another book, that is not usually a good enough reason to include multiple entries here
        (unless say, both the original and a translation were published in the same "Bible").

This file can never adequately represent all possible historical Bible books codes (and their mappings),
    especially since it attempts to avoid including historic codes which were not consistent or logical.

The data is preceded by a header of the same format as an OSIS header.

Note that the data is supplied as XML elements (not attributes).

Although an internal DTD is included, a Relax NG (RNC) schema is also supplied for better validation.

See the supplied BibleBooksCodes.ReadMe.txt for more details.
-->

<!DOCTYPE BibleBooksCodes [
    <!ELEMENT BibleBooksCodes (header,BibleBookCodes+)>
        <!ELEMENT header (revisionDesc*,work)>
            <!ELEMENT revisionDesc (date,p+)>
                <!ELEMENT date (#PCDATA)>
                <!ELEMENT p (#PCDATA)>
            <!ELEMENT work (version,date,title,contributor+,identifier+,rights)>
                <!ELEMENT version (#PCDATA)>
                <!ELEMENT title (#PCDATA)>
                <!ELEMENT contributor (#PCDATA)>
                    <!ATTLIST contributor role (com|edt) #REQUIRED>
                <!ELEMENT identifier (#PCDATA)>
                    <!ATTLIST identifier type (URL) #REQUIRED>
                <!ELEMENT rights (#PCDATA)>
        <!ELEMENT BibleBookCodes (originalLanguageCode, bookName,bookNameEnglishGuide,referenceAbbreviation,referenceNumber,sequenceNumber,expectedChapters?,
                        shortAbbreviation?,SBLAbbreviation?,OSISAbbreviation?,SwordAbbreviation?,CCELNumber?,USFMAbbreviation?,USFMNumber?,
                        USXNumber?,UnboundCode?,BibleditNumber?,
                        LogosNumber?,LogosAbbreviation?,
                        NETBibleAbbreviation?,DrupalBibleAbbreviation?,
                        BibleWorksAbbreviation?, ByzantineAbbreviation?,
                        possibleAlternativeAbbreviations?,possibleAlternativeBooks?,consistsOfBooks?,
                        typicalSection,typicalSubsection?)>
            <!ELEMENT originalLanguageCode (#PCDATA)>
            <!ELEMENT bookName (#PCDATA)>
            <!ELEMENT bookNameEnglishGuide (#PCDATA)>
            <!ELEMENT referenceAbbreviation (#PCDATA)>
            <!ELEMENT referenceNumber (#PCDATA)>
            <!ELEMENT sequenceNumber (#PCDATA)>
            <!ELEMENT expectedChapters (#PCDATA)>
            <!ELEMENT shortAbbreviation (#PCDATA)>
            <!ELEMENT SBLAbbreviation (#PCDATA)>
            <!ELEMENT OSISAbbreviation (#PCDATA)>
            <!ELEMENT SwordAbbreviation (#PCDATA)>
            <!ELEMENT CCELNumber (#PCDATA)>
            <!ELEMENT USFMAbbreviation (#PCDATA)>
            <!ELEMENT USFMNumber (#PCDATA)>
            <!ELEMENT USXNumber (#PCDATA)>
            <!ELEMENT UnboundCode (#PCDATA)>
            <!ELEMENT BibleditNumber (#PCDATA)>
            <!ELEMENT LogosNumber (#PCDATA)>
            <!ELEMENT LogosAbbreviation (#PCDATA)>
            <!ELEMENT NETBibleAbbreviation (#PCDATA)>
            <!ELEMENT DrupalBibleAbbreviation (#PCDATA)>
            <!ELEMENT BibleWorksAbbreviation (#PCDATA)>
            <!ELEMENT ByzantineAbbreviation (#PCDATA)>
            <!ELEMENT possibleAlternativeAbbreviations (#PCDATA)>
            <!ELEMENT possibleAlternativeBooks (#PCDATA)>
            <!ELEMENT consistsOfBooks (#PCDATA)>
            <!ELEMENT typicalSection (#PCDATA)>
            <!ELEMENT typicalSubsection (#PCDATA)>
]>

<BibleBooksCodes>

  <header>
    <work>
      <version>0.92</version>
      <date>2025-11-01</date>
      <title>Bible books codes list</title>
      <contributor role="com">Robert Hunt</contributor>
      <identifier type="URL">https://ubsicap.github.io/usfm/identification/books.html</identifier>
      <identifier type="URL">http://www.sbl-site.org/publications/publishingwithsbl.aspx</identifier>
      <identifier type="URL">http://www.bibletechnologies.net</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/news.php?item.9.4</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/request.php?canonicalissuesinparatext.pdf</identifier>
      <identifier type="URL">http://lc.bfbs.org.uk/e107_files/downloads/canonicalissuesinparatext.pdf</identifier> <!-- Alternative to above -->
      <identifier type="URL">http://www.crosswire.org/wiki/OSIS_Book_Abbreviations</identifier>
      <identifier type="URL">http://www.ethiopianorthodox.org/biography/01thelawofkings.pdf</identifier>
      <identifier type="URL">http://unbound.biola.edu/index.cfm?method=unbound.showFAQ&amp;faq_name=Bible_Index_Codes</identifier>
      <identifier type="URL">http://www.bibleworks.com/bw9help/bwh42_Abbreviations.htm</identifier>
      <identifier type="URL">https://github.com/Clear-Bible/Biblelib/blob/main/biblelib/books/books.tsv</identifier>
      <identifier type="URL">https://wiki.logos.com/COM_API_Bible_Book_Abbreviations</identifier>
      <rights>Public Domain</rights>
    </work>
  </header>

<!-- Old Testament -->
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>בְּרֵאשִׁית</bookName>
    <bookNameEnglishGuide>Genesis / 1 Moses</bookNameEnglishGuide>
    <referenceAbbreviation>GEN</referenceAbbreviation>
    <referenceNumber>1</referenceNumber>
    <sequenceNumber>20</sequenceNumber>
    <expectedChapters>50</expectedChapters>
    <shortAbbreviation>Ge</shortAbbreviation>
    <SBLAbbreviation>Gen</SBLAbbreviation>
    <OSISAbbreviation>Gen</OSISAbbreviation>
    <SwordAbbreviation>Gen</SwordAbbreviation>
    <CCELNumber>1</CCELNumber>
    <USFMAbbreviation>Gen</USFMAbbreviation>
    <USFMNumber>01</USFMNumber>
    <USXNumber>001</USXNumber>
    <UnboundCode>01O</UnboundCode>
    <BibleditNumber>1</BibleditNumber>
    <LogosNumber>1</LogosNumber>
    <LogosAbbreviation>Ge</LogosAbbreviation>
    <NETBibleAbbreviation>Gen</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Gen</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>GEN</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>GENE,GNSS,1 MSS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Pentateuch</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>שְׁמֹות</bookName>
    <bookNameEnglishGuide>Exodus / 2 Moses</bookNameEnglishGuide>
    <referenceAbbreviation>EXO</referenceAbbreviation>
    <referenceNumber>2</referenceNumber>
    <sequenceNumber>22</sequenceNumber>
    <expectedChapters>40</expectedChapters>
    <shortAbbreviation>Ex</shortAbbreviation>
    <SBLAbbreviation>Exod</SBLAbbreviation>
    <OSISAbbreviation>Exod</OSISAbbreviation>
    <SwordAbbreviation>Exod</SwordAbbreviation>
    <CCELNumber>2</CCELNumber>
    <USFMAbbreviation>Exo</USFMAbbreviation>
    <USFMNumber>02</USFMNumber>
    <USXNumber>002</USXNumber>
    <UnboundCode>02O</UnboundCode>
    <BibleditNumber>2</BibleditNumber>
    <LogosNumber>2</LogosNumber>
    <LogosAbbreviation>Ex</LogosAbbreviation>
    <NETBibleAbbreviation>Exo</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Exo</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>EXO</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>EXDS,2 MSS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Pentateuch</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>וַיִּקְרָא</bookName>
    <bookNameEnglishGuide>Leviticus / 3 Moses</bookNameEnglishGuide>
    <referenceAbbreviation>LEV</referenceAbbreviation>
    <referenceNumber>3</referenceNumber>
    <sequenceNumber>24</sequenceNumber>
    <expectedChapters>27</expectedChapters>
    <shortAbbreviation>Le</shortAbbreviation>
    <SBLAbbreviation>Lev</SBLAbbreviation>
    <OSISAbbreviation>Lev</OSISAbbreviation>
    <SwordAbbreviation>Lev</SwordAbbreviation>
    <CCELNumber>3</CCELNumber>
    <USFMAbbreviation>Lev</USFMAbbreviation>
    <USFMNumber>03</USFMNumber>
    <USXNumber>003</USXNumber>
    <UnboundCode>03O</UnboundCode>
    <BibleditNumber>3</BibleditNumber>
    <LogosNumber>3</LogosNumber>
    <LogosAbbreviation>Le</LogosAbbreviation>
    <NETBibleAbbreviation>Lev</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Lev</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>LEV</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>LVT,3 MSS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Pentateuch</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>בְּמִדְבַּר</bookName>
    <bookNameEnglishGuide>Numbers / 4 Moses</bookNameEnglishGuide>
    <referenceAbbreviation>NUM</referenceAbbreviation>
    <referenceNumber>4</referenceNumber>
    <sequenceNumber>26</sequenceNumber>
    <expectedChapters>36</expectedChapters>
    <shortAbbreviation>Nu</shortAbbreviation>
    <SBLAbbreviation>Num</SBLAbbreviation>
    <OSISAbbreviation>Num</OSISAbbreviation>
    <SwordAbbreviation>Num</SwordAbbreviation>
    <CCELNumber>4</CCELNumber>
    <USFMAbbreviation>Num</USFMAbbreviation>
    <USFMNumber>04</USFMNumber>
    <USXNumber>004</USXNumber>
    <UnboundCode>04O</UnboundCode>
    <BibleditNumber>4</BibleditNumber>
    <LogosNumber>4</LogosNumber>
    <LogosAbbreviation>Nu</LogosAbbreviation>
    <NETBibleAbbreviation>Num</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Num</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>NUM</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>NMBRS,4 MSS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Pentateuch</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>דְּבָרִים</bookName>
    <bookNameEnglishGuide>Deuteronomy / 5 Moses</bookNameEnglishGuide>
    <referenceAbbreviation>DEU</referenceAbbreviation>
    <referenceNumber>5</referenceNumber>
    <sequenceNumber>28</sequenceNumber>
    <expectedChapters>34</expectedChapters>
    <shortAbbreviation>Dt</shortAbbreviation>
    <SBLAbbreviation>Deut</SBLAbbreviation>
    <OSISAbbreviation>Deut</OSISAbbreviation>
    <SwordAbbreviation>Deut</SwordAbbreviation>
    <CCELNumber>5</CCELNumber>
    <USFMAbbreviation>Deu</USFMAbbreviation>
    <USFMNumber>05</USFMNumber>
    <USXNumber>005</USXNumber>
    <UnboundCode>05O</UnboundCode>
    <BibleditNumber>5</BibleditNumber>
    <LogosNumber>5</LogosNumber>
    <LogosAbbreviation>Dt</LogosAbbreviation>
    <NETBibleAbbreviation>Deu</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Deu</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>DEU</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>DTRN,5 MSS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Pentateuch</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>יְהוֹשֻעַ</bookName>
    <bookNameEnglishGuide>Joshua / Joshua son of Nun</bookNameEnglishGuide> <!-- See also Joshua A and Joshua B -->
    <referenceAbbreviation>JOS</referenceAbbreviation>
    <referenceNumber>6</referenceNumber>
    <sequenceNumber>30</sequenceNumber>
    <expectedChapters>24</expectedChapters>
    <shortAbbreviation>Jos</shortAbbreviation>
    <SBLAbbreviation>Josh</SBLAbbreviation>
    <OSISAbbreviation>Josh</OSISAbbreviation>
    <SwordAbbreviation>Josh</SwordAbbreviation>
    <CCELNumber>6</CCELNumber>
    <USFMAbbreviation>Jos</USFMAbbreviation>
    <USFMNumber>06</USFMNumber>
    <USXNumber>006</USXNumber>
    <UnboundCode>06O</UnboundCode>
    <BibleditNumber>6</BibleditNumber>
    <LogosNumber>6</LogosNumber>
    <LogosAbbreviation>Jos</LogosAbbreviation>
    <NETBibleAbbreviation>Jos</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Jos</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>JOS</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>JS,JSH</possibleAlternativeAbbreviations>
    <possibleAlternativeBooks>JSA</possibleAlternativeBooks>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>שֹׁפְטִים</bookName>
    <bookNameEnglishGuide>Judges</bookNameEnglishGuide> <!-- See also Judges A and Judges B -->
    <referenceAbbreviation>JDG</referenceAbbreviation>
    <referenceNumber>7</referenceNumber>
    <sequenceNumber>32</sequenceNumber>
    <expectedChapters>21</expectedChapters>
    <shortAbbreviation>Jdg</shortAbbreviation>
    <SBLAbbreviation>Judg</SBLAbbreviation>
    <OSISAbbreviation>Judg</OSISAbbreviation>
    <SwordAbbreviation>Judg</SwordAbbreviation>
    <CCELNumber>7</CCELNumber>
    <USFMAbbreviation>Jdg</USFMAbbreviation>
    <USFMNumber>07</USFMNumber>
    <USXNumber>007</USXNumber>
    <UnboundCode>07O</UnboundCode>
    <BibleditNumber>7</BibleditNumber>
    <LogosNumber>7</LogosNumber>
    <LogosAbbreviation>Jdg</LogosAbbreviation>
    <NETBibleAbbreviation>Jdg</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Jug</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>JDG</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>JG,JDGS</possibleAlternativeAbbreviations>
    <possibleAlternativeBooks>JGB</possibleAlternativeBooks>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>רוּת</bookName>
    <bookNameEnglishGuide>Ruth</bookNameEnglishGuide>
    <referenceAbbreviation>RUT</referenceAbbreviation>
    <referenceNumber>8</referenceNumber>
    <sequenceNumber>34</sequenceNumber>
    <expectedChapters>4</expectedChapters>
    <shortAbbreviation>Ru</shortAbbreviation>
    <SBLAbbreviation>Ruth</SBLAbbreviation>
    <OSISAbbreviation>Ruth</OSISAbbreviation>
    <SwordAbbreviation>Ruth</SwordAbbreviation>
    <CCELNumber>8</CCELNumber>
    <USFMAbbreviation>Rut</USFMAbbreviation>
    <USFMNumber>08</USFMNumber>
    <USXNumber>008</USXNumber>
    <UnboundCode>08O</UnboundCode>
    <BibleditNumber>8</BibleditNumber>
    <LogosNumber>8</LogosNumber>
    <LogosAbbreviation>Ru</LogosAbbreviation>
    <NETBibleAbbreviation>Rut</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Rut</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>RUT</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>RTH</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>שְׁמוּאֵל א</bookName>
    <bookNameEnglishGuide>1 Samuel / 1 Kingdoms / 1 Kings</bookNameEnglishGuide>
    <referenceAbbreviation>SA1</referenceAbbreviation>
    <referenceNumber>9</referenceNumber>
    <sequenceNumber>38</sequenceNumber>
    <expectedChapters>31</expectedChapters>
    <shortAbbreviation>1Sa</shortAbbreviation>
    <SBLAbbreviation>1 Sam</SBLAbbreviation>
    <OSISAbbreviation>1Sam</OSISAbbreviation>
    <SwordAbbreviation>1Sam</SwordAbbreviation>
    <CCELNumber>9</CCELNumber>
    <USFMAbbreviation>1Sa</USFMAbbreviation>
    <USFMNumber>09</USFMNumber>
    <USXNumber>009</USXNumber>
    <UnboundCode>09O</UnboundCode>
    <BibleditNumber>9</BibleditNumber>
    <LogosNumber>9</LogosNumber>
    <LogosAbbreviation>1Sa</LogosAbbreviation>
    <NETBibleAbbreviation>1Sa</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>1Sm</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>1SA</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>1 SML,1 KNGDMS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>שְׁמוּאֵל ב</bookName>
    <bookNameEnglishGuide>2 Samuel / 2 Kingdoms / 2 Kings</bookNameEnglishGuide>
    <referenceAbbreviation>SA2</referenceAbbreviation>
    <referenceNumber>10</referenceNumber>
    <sequenceNumber>40</sequenceNumber>
    <expectedChapters>24</expectedChapters>
    <shortAbbreviation>2Sa</shortAbbreviation>
    <SBLAbbreviation>2 Sam</SBLAbbreviation>
    <OSISAbbreviation>2Sam</OSISAbbreviation>
    <SwordAbbreviation>2Sam</SwordAbbreviation>
    <CCELNumber>10</CCELNumber>
    <USFMAbbreviation>2Sa</USFMAbbreviation>
    <USFMNumber>10</USFMNumber>
    <USXNumber>010</USXNumber>
    <UnboundCode>10O</UnboundCode>
    <BibleditNumber>10</BibleditNumber>
    <LogosNumber>10</LogosNumber>
    <LogosAbbreviation>2Sa</LogosAbbreviation>
    <NETBibleAbbreviation>2Sa</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>2Sm</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>2SA</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>2 SML,2 KNGDMS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>מְלָכִים א</bookName>
    <bookNameEnglishGuide>1 Kings / 3 Kingdoms / 3 Kings</bookNameEnglishGuide>
    <referenceAbbreviation>KI1</referenceAbbreviation>
    <referenceNumber>11</referenceNumber>
    <sequenceNumber>44</sequenceNumber>
    <expectedChapters>22</expectedChapters>
    <shortAbbreviation>1Ki</shortAbbreviation>
    <SBLAbbreviation>1 Kgs</SBLAbbreviation>
    <OSISAbbreviation>1Kgs</OSISAbbreviation>
    <SwordAbbreviation>1Kgs</SwordAbbreviation>
    <CCELNumber>11</CCELNumber>
    <USFMAbbreviation>1Ki</USFMAbbreviation>
    <USFMNumber>11</USFMNumber>
    <USXNumber>011</USXNumber>
    <UnboundCode>11O</UnboundCode>
    <BibleditNumber>11</BibleditNumber>
    <LogosNumber>11</LogosNumber>
    <LogosAbbreviation>1Ki</LogosAbbreviation>
    <NETBibleAbbreviation>1Ki</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>1Kg</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>1KI</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>1 KINGS,1 KING,1 KIN,1 KNGS,3 KNGDMS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>מְלָכִים ב</bookName>
    <bookNameEnglishGuide>2 Kings / 4 Kingdoms / 4 Kings</bookNameEnglishGuide>
    <referenceAbbreviation>KI2</referenceAbbreviation>
    <referenceNumber>12</referenceNumber>
    <sequenceNumber>46</sequenceNumber>
    <expectedChapters>25</expectedChapters>
    <shortAbbreviation>2Ki</shortAbbreviation>
    <SBLAbbreviation>2 Kgs</SBLAbbreviation>
    <OSISAbbreviation>2Kgs</OSISAbbreviation>
    <SwordAbbreviation>2Kgs</SwordAbbreviation>
    <CCELNumber>12</CCELNumber>
    <USFMAbbreviation>2Ki</USFMAbbreviation>
    <USFMNumber>12</USFMNumber>
    <USXNumber>012</USXNumber>
    <UnboundCode>12O</UnboundCode>
    <BibleditNumber>12</BibleditNumber>
    <LogosNumber>12</LogosNumber>
    <LogosAbbreviation>2Ki</LogosAbbreviation>
    <NETBibleAbbreviation>2Ki</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>2Kg</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>2KI</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>2 KINGS,2 KING,2 KIN,2 KNGS,4 KNGDMS</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>דִּבְרֵי הַיָּמִים א</bookName>
    <bookNameEnglishGuide>1 Chronicles / 1 Paralipomenon</bookNameEnglishGuide>
    <referenceAbbreviation>CH1</referenceAbbreviation>
    <referenceNumber>13</referenceNumber>
    <sequenceNumber>50</sequenceNumber>
    <expectedChapters>29</expectedChapters>
    <shortAbbreviation>1Ch</shortAbbreviation>
    <SBLAbbreviation>1 Chr</SBLAbbreviation>
    <OSISAbbreviation>1Chr</OSISAbbreviation>
    <SwordAbbreviation>1Chr</SwordAbbreviation>
    <CCELNumber>13</CCELNumber>
    <USFMAbbreviation>1Ch</USFMAbbreviation>
    <USFMNumber>13</USFMNumber>
    <USXNumber>013</USXNumber>
    <UnboundCode>13O</UnboundCode>
    <BibleditNumber>13</BibleditNumber>
    <LogosNumber>13</LogosNumber>
    <LogosAbbreviation>1Ch</LogosAbbreviation>
    <NETBibleAbbreviation>1Ch</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>1Ch</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>1CH</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>1 CHRN</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>דִּבְרֵי הַיָּמִים ב</bookName>
    <bookNameEnglishGuide>2 Chronicles / 2 Paralipomenon</bookNameEnglishGuide>
    <referenceAbbreviation>CH2</referenceAbbreviation>
    <referenceNumber>14</referenceNumber>
    <sequenceNumber>52</sequenceNumber>
    <expectedChapters>36,37</expectedChapters>
    <shortAbbreviation>2Ch</shortAbbreviation>
    <SBLAbbreviation>2 Chr</SBLAbbreviation>
    <OSISAbbreviation>2Chr</OSISAbbreviation>
    <SwordAbbreviation>2Chr</SwordAbbreviation>
    <CCELNumber>14</CCELNumber>
    <USFMAbbreviation>2Ch</USFMAbbreviation>
    <USFMNumber>14</USFMNumber>
    <USXNumber>014</USXNumber>
    <UnboundCode>14O</UnboundCode>
    <BibleditNumber>14</BibleditNumber>
    <LogosNumber>14</LogosNumber>
    <LogosAbbreviation>2Ch</LogosAbbreviation>
    <NETBibleAbbreviation>2Ch</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>2Ch</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>2CH</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>2 CHRN</possibleAlternativeAbbreviations>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <!-- Don't use this for combined Ezra-Nehemiah (use EZN) -->
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>עֶזְרָא</bookName>
    <bookNameEnglishGuide>Ezra / 1 Ezra / 1 Esdras</bookNameEnglishGuide>
    <referenceAbbreviation>EZR</referenceAbbreviation>
    <referenceNumber>15</referenceNumber>
    <sequenceNumber>60</sequenceNumber>
    <expectedChapters>10</expectedChapters>
    <shortAbbreviation>Ezr</shortAbbreviation>
    <SBLAbbreviation>Ezra</SBLAbbreviation>
    <OSISAbbreviation>Ezra</OSISAbbreviation>
    <SwordAbbreviation>Ezra</SwordAbbreviation>
    <CCELNumber>15</CCELNumber>
    <USFMAbbreviation>Ezr</USFMAbbreviation>
    <USFMNumber>15</USFMNumber>
    <USXNumber>015</USXNumber>
    <UnboundCode>15O</UnboundCode>
    <BibleditNumber>15</BibleditNumber>
    <LogosNumber>15</LogosNumber>
    <LogosAbbreviation>Ezr</LogosAbbreviation>
    <NETBibleAbbreviation>Ezr</NETBibleAbbreviation>
    <DrupalBibleAbbreviation>Ezr</DrupalBibleAbbreviation>
    <BibleWorksAbbreviation>EZR</BibleWorksAbbreviation>
    <possibleAlternativeAbbreviations>EZRA</possibleAlternativeAbbreviations>
    <possibleAlternativeBooks>EZN</possibleAlternativeBooks>
    <typicalSection>OT</typicalSection>
    <typicalSubsection>Historical</typicalSubsection>
  </BibleBookCodes>
  <BibleBookCodes>
    <originalLanguageCode>hbo</originalLanguageCode>
    <bookName>נְחֶמְיָה</bookName>